### ISSUE TITLE
XSS in Whois

### ISSUE THREAD

**Issue by prauscher** [tmshlvck/ulg#12]
If my whois-information contain HTML (and as such, escaped javascript-code), they do not get escaped before getting printed.
E.g. http://bgp.freifunk-bielefeld.de/ulg/ulg.py => show routing table ebgp for 172.22.120.0/26 => click on AS64720 and get a nice and pretty javascript-alert ;)

**Comment by tmshlvck** [comment]
Hello Patrick!

Thanks for the report! You were right. There was Markup() object passed to the Genshi that allowed leak the raw text from the whois binary to the resulting Webpage. Fixed in the latest commit.

Tomas
