### ISSUE TITLE
support for IOS-XR based Ciscos

### ISSUE THREAD

**Issue by kb70** [tmshlvck/ulg#9]
the current version gives an error when trying to access an IOS-XR based Cisco Router (ASR9k in our case):
<type 'exceptions.Exception'>: pexpect session failed: Connection timeout. 
      args = ('pexpect session failed: Connection timeout.',) 
      message = 'pexpect session failed: Connection timeout.'

This is when the website is called initially. If we can be of any help in testing/debugging please get in contact with me.

**Comment by tmshlvck** [comment]
Just closing old issue... Support for IOS-XR is already present.
